// components/Layout.jsx
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { useSessionData } from "@/hooks/SessionHooks";
import React from "react";

const geistSans = {
  variable: "--font-geist-sans",
  subsets: ["latin"],
};

const geistMono = {
  variable: "--font-geist-mono",
  subsets: ["latin"],
};

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <div className="dashboard-content">
      <SidebarProvider
        style={{ "--sidebar-width": "18rem", "--header-height": "3rem" }}
      >
        <AppSidebar variant="inset" />
        <SidebarInset>{children}</SidebarInset>
      </SidebarProvider>
    </div>
  );
};

export default Layout;
