// components/Layout.jsx
import SideBarComponent from "@/components/ui/sidebar-component";
import UserProfileLoadingScreen from "@/components/ui/userData-loading";
import React, { Suspense } from "react";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <div className="dashboard-content">
      <Suspense fallback={<UserProfileLoadingScreen />}>
        <SideBarComponent children={children}></SideBarComponent>
      </Suspense>
    </div>
  );
};

export default Layout;
